experiment:
  horizon: 60
  context_length: 60
  n_splits: 3
  test_size: 60
  random_seed: 42

models:
  moirai_small: "Salesforce/moirai-1.1-R-small"
  moirai_base: "Salesforce/moirai-1.1-R-base"

datasets:
  SPY:
    type: "yahoo"
    ticker: "SPY"
    frequency: "B"
    seasonality: 5
    start_date: "2015-01-01"
    end_date: "2024-12-31"

  AQI_LA:
    type: "aqi"
    lat: 34.0522
    lon: -118.2437
    frequency: "D"
    seasonality: 7
    start_date: "2022-08-10"
    end_date: "2024-12-31"